# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  database:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - orb: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_USER: circleci
    steps:
      - run: apk add alpine-sdk
      - run: apk add clang
      - run: wget -O pg_partman.tar.gz "https://github.com/pgpartman/pg_partman/archive/v4.2.2.tar.gz"
      - run: mkdir -p /usr/src/pg_partman
      - run: tar --extract --file pg_partman.tar.gz --directory /usr/src/pg_partman --strip-components 1
      - run: rm pg_partman.tar.gz
      - run: ls -al /usr/src/pg_partman
      - run: make -C /usr/src/pg_partman
      - run: make -C /usr/src/pg_partman NO_BGW=1 install
      - run: rm -rf /usr/src/pg_partman
